package trabalho.conclusao;
//
//Automatically generated by XACDML
//

import simula.manager.*;
public class Main
{
    public static void main (String args[])
    {
        System.out.println("\nGeracao de Door Control Simulation atraves de Simulation Manager");
        SimulationManager man= new SimulationManager();

        QueueEntry qe;//queues
        ResourceEntry re;//resource queues
        ExternalActiveEntry eae;//generator and detroy
        InternalActiveEntry iae;//activivity and router
        ObserverEntry oe;
        HistogramEntry he;

        //queues
        qe = new QueueEntry();
        qe.SetId("WAIT_OPEN_DOOR"); // Esperando comando para abrir a porta
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("WAIT_DOOR_ACTUATOR"); // Esperando atuador
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("WAIT_DOOR_SENSORS"); // Esperando sensores
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("WAIT_FEEDBACK"); // Esperando feedback
        man.AddQueue(qe);

        //observers
        oe = new ObserverEntry(ObserverEntry.QUEUE, "WAIT_OPEN_DOOR");
        oe.SetId("OBS_OPEN_DOOR");
        man.AddObserver(oe);

        oe = new ObserverEntry(ObserverEntry.QUEUE, "WAIT_DOOR_ACTUATOR");
        oe.SetId("OBS_SENSORS");
        man.AddObserver(oe);

        oe = new ObserverEntry(ObserverEntry.QUEUE, "WAIT_DOOR_SENSORS");
        oe.SetId("OBS_SENSORS");
        man.AddObserver(oe);

        oe = new ObserverEntry(ObserverEntry.QUEUE, "WAIT_FEEDBACK");
        oe.SetId("OBS_FEEDBACK");
        man.AddObserver(oe);



        //generate the model

        if (man.GenerateModel())
            System.out.println("\nModel successfuly generated!");
        else
        {
            System.out.println("\nThere was an errors during the model generation!");
            System.out.println("Exiting...");
            return;
        }

        //start the simulation

        System.out.println("Starting the simulation. Simulation wil run unitl time=500");

        man.ExecuteSimulation(500);

        while (!man.Finished())
        {
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException e) {break;}
        }

        System.out.println("Simulation Stopped!");

        //finally, output the results

        man.OutputSimulationResults ("HBC.out");



        System.out.println("\nThat's all folks!");
    }
}
