package examples;
//
//Automatically generated by XACDML
//

import simula.manager.*;
public class BANK
{
    public static void main (String args[])
    {
        System.out.println("\nGeracao de BANK atraves de Simulation Manager");
        SimulationManager man= new SimulationManager();

        QueueEntry qe;//queues
        ResourceEntry re;//resource queues
        ExternalActiveEntry eae;//generator and destroy
        InternalActiveEntry iae;//activivity and router
        InterruptActiveEntry intae;//interrupts
        ObserverEntry oe;
        HistogramEntry he;

        //queues and observer queues


        qe = new QueueEntry();
        qe.SetId("QUEUE");//mapped by dead id
        man.AddQueue(qe);


        qe = new QueueEntry();
        qe.SetId("WAIT");//mapped by dead id
        man.AddQueue(qe);

        re = new ResourceEntry();
        re.SetId("IDLE");//mapped by dead id
        re.setInit((short) 3);
        man.AddResource(re);
        //active states

        //externals (generates and destroys)

        eae = new ExternalActiveEntry(true); //generate
        eae.SetId("ARRIVAL"); //mapped by generate id
        eae.setQID("QUEUE"); // mapped by next dead
        eae.setServiceDist( ActiveEntry.NEGEXP);// mapped by stat type
        eae.setDistP1((int)10);// mapped by parm1
        man.AddActiveState(eae);

        eae = new ExternalActiveEntry(false); //destroy
        eae.SetId( "OUT"); //mapped by destroy id
        eae.setQID( "WAIT"); // mapped by prev dead
        man.AddActiveState(eae);


        //internals (activities and routers)


        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "SERVICE"); //mapped by act id
        iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
        iae.setDistP1((int)6);// mapped by parm1
        iae.setDistP2((int)12); //mapped by parm2
        iae.addCond("true");
        iae.addToQueue("WAIT");// mapped by next dead
        iae.addFromQueue("QUEUE");// mapped by prev dead
        iae.addToResource("IDLE");// mapped by next resource dead
        iae.addResourceQty(new Integer(3));// mapped by init on resource dead
        iae.addFromResource("IDLE");// mapped by prev resource dead
        man.AddActiveState(iae);

        //observers

        //generate the model

        if (man.GenerateModel())
            System.out.println("\nModel successfuly generated!");
        else
        {
            System.out.println("\nThere was an errors during the model generation!");
            System.out.println("Exiting...");
            return;
        }

        //start the simulation

        System.out.println("Starting the simulation. Simulation wil run unitl time=500");

        man.ExecuteSimulation(500);

        while (!man.Finished())
        {
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException e) {break;}
        }

        System.out.println("Simulation Stopped!");

        //finally, output the results

        man.OutputSimulationResults ("BANK.out");


        System.out.println("\nThat's all folks!");
    }
}