package examples;
//
//Automatically generated by XACDML
//
import simula.manager.*;

public class CSNewParameters_OneControlLoop
{
    public static void main (String args[])
    {
        //CS reduzida, não contem generate vehicles, nem API, nem FB2
        System.out.println("\nGeracao de CONTROL_STRUCTURE atraves de Simulation Manager");
        SimulationManager man= new SimulationManager();

        QueueEntry qe;//queues
        ResourceEntry re;//resource queues
        ExternalActiveEntry eae;//generator and detroy
        InternalActiveEntry iae;//activivity and router
        InterruptActiveEntry intae;//interrupts
        ObserverEntry oe;
        HistogramEntry he;

        //queues and observer queues

        qe = new QueueEntry();
        qe.SetId("Q_A1");//mapped by dead id
        //qe.setObsid("Q_A1_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_A2");//mapped by dead id
        //qe.setObsid("Q_A2_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_A3");//mapped by dead id
        //qe.setObsid("Q_A3_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_FB3");//mapped by dead id
        //qe.setObsid("Q_FB3_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_FB4");//mapped by dead id
        //qe.setObsid("Q_FB4_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_FB5");//mapped by dead id
        //qe.setObsid("Q_FB5_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_FB6");//mapped by dead id
        //qe.setObsid("Q_FB6_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_FB7");//mapped by dead id
        //qe.setObsid("Q_FB7_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_OUT");//mapped by dead id
        qe.setObsid("Q_OUT_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_GENERATE_CONTROL_ACTION");//mapped by dead id
        //qe.setObsid("Q_GENERATE_CONTROL_ACTION_OBS");//observer
        man.AddQueue(qe);

        qe = new QueueEntry();
        qe.SetId("Q_CONTROL_ALG");//mapped by dead id
        //qe.setObsid("Q_CONTROL_ALG_OBS");//observer
        man.AddQueue(qe);

        re = new ResourceEntry();
        re.SetId("TRAFFIC_AGENT");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        re = new ResourceEntry();
        re.SetId("SCCI_MODULE");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        re = new ResourceEntry();
        re.SetId("TRAFFIC_LIGHTS");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        re = new ResourceEntry();
        re.SetId("N_TRAFFIC_SENSOR_1");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        re = new ResourceEntry();
        re.SetId("N_TRAFFIC_SENSOR_2");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        re = new ResourceEntry();
        re.SetId("P_TRAFFIC_SENSOR_1");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        re = new ResourceEntry();
        re.SetId("P_TRAFFIC_SENSOR_2");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        re = new ResourceEntry();
        re.SetId("INTERSECTION");//mapped by dead id
        re.setInit((short) 1);
        man.AddResource(re);
        //active states

        //externals (generates and destroys)
        eae = new ExternalActiveEntry(true); //generate
        eae.SetId("GENERATE_CONTROL_ACTION"); //mapped by generate id
        eae.setQID("Q_GENERATE_CONTROL_ACTION"); // mapped by next dead
        eae.setServiceDist( ActiveEntry.NEGEXP);// mapped by stat type
        eae.setDistP1((int)17.5);// mapped by parm1
        man.AddActiveState(eae);

        eae = new ExternalActiveEntry(false); //destroy
        eae.SetId( "OUT"); //mapped by destroy id
        eae.setQID( "Q_OUT"); // mapped by prev dead
        man.AddActiveState(eae);

        //internals (activities and routers)

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "ACT_CONTROL_ALG"); //mapped by act id
        iae.setServiceDist(ActiveEntry.CONST);// mapped by stat type
        iae.setDistP1((int)1);// mapped by parm1
        iae.addCond("true");
        iae.addToQueue("Q_CONTROL_ALG");// mapped by next dead
        iae.addFromQueue("Q_A1");// mapped by prev dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "A_1"); //mapped by act id
        iae.setServiceDist(ActiveEntry.NORMAL);// mapped by stat type
        iae.setDistP1((int)20);// mapped by parm1
        iae.setDistP2((int)10); //mapped by parm2
        iae.addCond("true");
        iae.addToQueue("Q_A1");// mapped by next dead
        iae.addFromQueue("Q_GENERATE_CONTROL_ACTION");// mapped by prev dead
        iae.addToResource("TRAFFIC_AGENT");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("TRAFFIC_AGENT");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "A_2"); //mapped by act id
        iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
        iae.setDistP1((int)0.1);// mapped by parm1
        iae.setDistP2((int)0.5); //mapped by parm2
        iae.addCond("true");
        iae.addToQueue("Q_A2");// mapped by next dead
        iae.addFromQueue("Q_CONTROL_ALG");// mapped by prev dead
        iae.addToResource("SCCI_MODULE");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("SCCI_MODULE");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "A_3"); //mapped by act id
        iae.setServiceDist(ActiveEntry.NEGEXP);// mapped by stat type
        iae.setDistP1((int)20);// mapped by parm1
        iae.addCond("true");
        iae.addToQueue("Q_A3");// mapped by next dead
        iae.addFromQueue("Q_A2");// mapped by prev dead
        iae.addToResource("TRAFFIC_LIGHTS");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("TRAFFIC_LIGHTS");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "FB_1"); //mapped by act id
        iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
        iae.setDistP1((int)1);// mapped by parm1
        iae.setDistP2((int)5); //mapped by parm2
        iae.addCond("true");
        iae.addToQueue("Q_OUT");// mapped by next dead
        iae.addFromQueue("Q_FB7");// mapped by prev dead
        iae.addToResource("SCCI_MODULE");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("SCCI_MODULE");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "FB_3"); //mapped by act id
        iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
        iae.setDistP1((int)0);// mapped by parm1
        iae.setDistP2((int)1); //mapped by parm2
        iae.addCond("true");
        iae.addToQueue("Q_FB3");// mapped by next dead
        iae.addFromQueue("Q_A3");// mapped by prev dead
        iae.addToResource("INTERSECTION");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("INTERSECTION");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "FB_4"); //mapped by act id
        iae.setServiceDist(ActiveEntry.NORMAL);// mapped by stat type
        iae.setDistP1((int)1.25);// mapped by parm1
        iae.setDistP2((int)0.5); //mapped by parm2
        iae.addCond("true");
        iae.addToQueue("Q_FB4");// mapped by next dead
        iae.addFromQueue("Q_FB3");// mapped by prev dead
        iae.addToResource("P_TRAFFIC_SENSOR_1");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("P_TRAFFIC_SENSOR_1");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "FB_5"); //mapped by act id
        iae.setServiceDist(ActiveEntry.NEGEXP);// mapped by stat type
        iae.setDistP1((int)1.2);// mapped by parm1
        iae.addCond("true");
        iae.addToQueue("Q_FB5");// mapped by next dead
        iae.addFromQueue("Q_FB4");// mapped by prev dead
        iae.addToResource("P_TRAFFIC_SENSOR_2");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("P_TRAFFIC_SENSOR_2");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "FB_6"); //mapped by act id
        iae.setServiceDist(ActiveEntry.UNIFORM);// mapped by stat type
        iae.setDistP1((int)2);// mapped by parm1
        iae.setDistP2((int)5); //mapped by parm2
        iae.addCond("true");
        iae.addToQueue("Q_FB6");// mapped by next dead
        iae.addFromQueue("Q_FB5");// mapped by prev dead
        iae.addToResource("N_TRAFFIC_SENSOR_1");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("N_TRAFFIC_SENSOR_1");// mapped by prev resource dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "FB_7"); //mapped by act id
        iae.setServiceDist(ActiveEntry.NEGEXP);// mapped by stat type
        iae.setDistP1((int)6);// mapped by parm1
        iae.addCond("true");
        iae.addToQueue("Q_FB7");// mapped by next dead
        iae.addFromQueue("Q_FB6");// mapped by prev dead
        iae.addToResource("N_TRAFFIC_SENSOR_2");// mapped by next resource dead
        iae.addResourceQty(new Integer(1));// mapped by init on resource dead
        iae.addFromResource("N_TRAFFIC_SENSOR_2");// mapped by prev resource dead
        man.AddActiveState(iae);

        //observers

//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_A1");//observer queue
//        oe.SetId("Q_A1_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_A2");//observer queue
//        oe.SetId("Q_A2_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_A3");//observer queue
//        oe.SetId("Q_A3_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB3");//observer queue
//        oe.SetId("Q_FB3_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB4");//observer queue
//        oe.SetId("Q_FB4_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB5");//observer queue
//        oe.SetId("Q_FB5_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB6");//observer queue
//        oe.SetId("Q_FB6_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_FB7");//observer queue
//        oe.SetId("Q_FB7_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);

        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_OUT");//observer queue
        oe.SetId("Q_OUT_OBS");
        oe.setName(oe.GetId());
        man.AddObserver(oe);

//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_GENERATE_CONTROL_ACTION");//observer queue
//        oe.SetId("Q_GENERATE_CONTROL_ACTION_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);

//        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_CONTROL_ALG");//observer queue
//        oe.SetId("Q_CONTROL_ALG_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);

        oe= new ObserverEntry(ObserverEntry.ACTIVE,"GENERATE_CONTROL_ACTION");
        oe.SetId("GENERATE_CONTROL_ACTION_OBS");
        oe.setName(oe.GetId());
        man.AddObserver(oe);

        eae = (ExternalActiveEntry)man.GetActiveState("GENERATE_CONTROL_ACTION");
        eae.setObsid("GENERATE_CONTROL_ACTION_OBS");

//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"A_1");
//        oe.SetId("ACT_A1_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("A_1");
//        iae.setObsid("ACT_A1_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"A_2");
//        oe.SetId("ACT_A2_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("A_2");
//        iae.setObsid("ACT_A2_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"A_3");
//        oe.SetId("ACT_A3_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("A_3");
//        iae.setObsid("ACT_A3_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"FB_1");
//        oe.SetId("ACT_FB1_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("FB_1");
//        iae.setObsid("ACT_FB1_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"FB_3");
//        oe.SetId("ACT_FB3_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("FB_3");
//        iae.setObsid("ACT_FB3_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"FB_4");
//        oe.SetId("ACT_FB4_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("FB_4");
//        iae.setObsid("ACT_FB4_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"FB_5");
//        oe.SetId("ACT_FB5_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("FB_5");
//        iae.setObsid("ACT_FB5_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"FB_6");
//        oe.SetId("ACT_FB6_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("FB_6");
//        iae.setObsid("ACT_FB6_OBS");
//
//        oe= new ObserverEntry(ObserverEntry.ACTIVE,"FB_7");
//        oe.SetId("ACT_FB7_OBS");
//        oe.setName(oe.GetId());
//        man.AddObserver(oe);
//
//        iae = (InternalActiveEntry)man.GetActiveState("FB_7");
//        iae.setObsid("ACT_FB7_OBS");

        //generate the model

        if (man.GenerateModel())
            System.out.println("\nModel successfuly generated!");
        else
        {
            System.out.println("\nThere was an errors during the model generation!");
            System.out.println("Exiting...");
            return;
        }

        //start the simulation

        System.out.println("Starting the simulation. Simulation wil run unitl time=1000");

        man.ExecuteSimulation(1000);

        while (!man.Finished())
        {
            try
            {
                Thread.sleep(1000);
            }
            catch(InterruptedException e) {break;}
        }

        System.out.println("Simulation Stopped!");

        //finally, output the results

        man.OutputSimulationResults ("CONTROL_STRUCTURE_NEW_P_ONE_CONTROL_LOOP.out");


        System.out.println("\nThat's all folks!");
    }
}