package examples;
//
//Automatically generated by XACDML
//

import simula.manager.*;
public class TwoInOneOutAuto
{
    public static void main (String args[])
    {
        System.out.println("\nGeracao de CONTROL_STRUCTURE atraves de Simulation Manager");
        SimulationManager man= new SimulationManager();

        QueueEntry qe;//queues
        ResourceEntry re;//resource queues
        ExternalActiveEntry eae;//generator and detroy
        InternalActiveEntry iae;//activivity and router
        InterruptActiveEntry intae;//interrupts
        ObserverEntry oe;
        HistogramEntry he;

        //queues and observer queues


        qe = new QueueEntry();
        qe.SetId("Q_IN_1");//mapped by dead id
        qe.setObsid("Q_IN_1_OBS");//observer
        man.AddQueue(qe);


        qe = new QueueEntry();
        qe.SetId("Q_IN_2");//mapped by dead id
        qe.setObsid("Q_IN_2_OBS");//observer
        man.AddQueue(qe);


        qe = new QueueEntry();
        qe.SetId("Q_OUT");//mapped by dead id
        qe.setObsid("Q_OUT_OBS");//observer
        man.AddQueue(qe);

        //active states

        //externals (generates and destroys)
        eae = new ExternalActiveEntry(true); //generate
        eae.SetId("GENERATE_IN_1"); //mapped by generate id
        eae.setQID("Q_IN_1"); // mapped by next dead
        eae.setServiceDist( ActiveEntry.CONST);// mapped by stat type
        eae.setDistP1((int)100);// mapped by parm1
        man.AddActiveState(eae);

        eae = new ExternalActiveEntry(true); //generate
        eae.SetId("GENERATE_IN_2"); //mapped by generate id
        eae.setQID("Q_IN_2"); // mapped by next dead
        eae.setServiceDist( ActiveEntry.CONST);// mapped by stat type
        eae.setDistP1((int)250);// mapped by parm1
        man.AddActiveState(eae);


        //internals (activities and routers)
        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "A_1.1"); //mapped by act id
        iae.setServiceDist(ActiveEntry.CONST);// mapped by stat type
        iae.setDistP1((int)0);// mapped by parm1
        iae.addCond("true");
        iae.addToQueue("Q_OUT");// mapped by next dead
        iae.addFromQueue("Q_IN_1");// mapped by prev dead
        man.AddActiveState(iae);

        iae = new InternalActiveEntry(true); //isn't router
        iae.SetId( "A_1.2"); //mapped by act id
        iae.setServiceDist(ActiveEntry.CONST);// mapped by stat type
        iae.setDistP1((int)1);// mapped by parm1
        iae.addCond("true");
        iae.addToQueue("Q_OUT");// mapped by next dead
        iae.addFromQueue("Q_IN_2");// mapped by prev dead
        man.AddActiveState(iae);


        //observers
        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_IN_1");//observer queue
        oe.SetId("Q_IN_1_OBS");
        man.AddObserver(oe);

        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_IN_2");//observer queue
        oe.SetId("Q_IN_2_OBS");
        man.AddObserver(oe);

        oe= new ObserverEntry(ObserverEntry.QUEUE,"Q_OUT");//observer queue
        oe.SetId("Q_OUT_OBS");
        man.AddObserver(oe);

        oe= new ObserverEntry(ObserverEntry.ACTIVE,"GENERATE_IN_1");
        oe.SetId("GENERATE_IN_1_OBS");
        man.AddObserver(oe);

        eae = (ExternalActiveEntry)man.GetActiveState("GENERATE_IN_1");
        eae.setObsid("GENERATE_IN_1_OBS");

        oe= new ObserverEntry(ObserverEntry.ACTIVE,"GENERATE_IN_2");
        oe.SetId("GENERATE_IN_2_OBS");
        man.AddObserver(oe);

        eae = (ExternalActiveEntry)man.GetActiveState("GENERATE_IN_2");
        eae.setObsid("GENERATE_IN_2_OBS");

        oe= new ObserverEntry(ObserverEntry.ACTIVE,"A_1.1");
        oe.SetId("ACT_1_OBS");
        man.AddObserver(oe);

        iae = (InternalActiveEntry)man.GetActiveState("A_1.1");
        iae.setObsid("ACT_1_OBS");

        oe= new ObserverEntry(ObserverEntry.ACTIVE,"A_1.2");
        oe.SetId("ACT_2_OBS");
        man.AddObserver(oe);

        iae = (InternalActiveEntry)man.GetActiveState("A_1.2");
        iae.setObsid("ACT_2_OBS");


        //generate the model

        if (man.GenerateModel())
            System.out.println("\nModel successfuly generated!");
        else
        {
            System.out.println("\nThere was an errors during the model generation!");
            System.out.println("Exiting...");
            return;
        }

        //start the simulation

        System.out.println("Starting the simulation. Simulation wil run unitl time=500");

        man.ExecuteSimulation(500);

        while (!man.Finished())
        {
            try
            {
                Thread.sleep(500);
            }
            catch(InterruptedException e) {break;}
        }

        System.out.println("Simulation Stopped!");

        //finally, output the results

        man.OutputSimulationResults ("2in1outAuto.out");


        System.out.println("\nThat's all folks!");
    }
}